### ISSUE TITLE
Make file upload limit configurable

### ISSUE THREAD

**Issue by demiankatz** [FalveyLibraryTechnology/VuDL#231]
The file upload system currently has a hard-coded limit. Uploading files > 200MB yields:

`Internal Server Error: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Error: options.maxFileSize (209715200 bytes) exceeded, received 209730262 bytes of file data<br> &nbsp; &nbsp;at Stream.&lt;anonymous&gt; (/opt/vudl/api/node_modules/formidable/src/Formidable.js:358:11)<br> &nbsp; &nbsp;at Stream.emit (node:events:527:28)<br> &nbsp; &nbsp;at Stream.emit (node:domain:475:12)<br> &nbsp; &nbsp;at MultipartParser.dataPropagation (/opt/vudl/api/node_modules/formidable/src/plugins/multipart.js:104:22)<br> &nbsp; &nbsp;at MultipartParser.emit (node:events:539:35)<br> &nbsp; &nbsp;at MultipartParser.emit (node:domain:475:12)<br> &nbsp; &nbsp;at addChunk (node:internal/streams/readable:315:12)<br> &nbsp; &nbsp;at readableAddChunk (node:internal/streams/readable:289:9)<br> &nbsp; &nbsp;at MultipartParser.Readable.push (node:internal/streams/readable:228:10)<br> &nbsp; &nbsp;at MultipartParser._handleCallback (/opt/vudl/api/node_modules/formidable/src/parsers/Multipart.js:100:10)</pre> </body> </html> `

We should make this limit configurable.

**Comment by demiankatz** [comment]
Fixed by #262.
